server:
  port: 9022

spring:
  application:
    name: spring-cloud-client
  profiles:
    active: dev #@spring.profiles.active@
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

# Swagger界面内容配置
swagger:
  title: spring-cloud-client-backend API接口文档
  description: spring-cloud-client-backend Api Documentation
  version: 1.0.0
  show: true
  contact:
    name: wulinyun
    url:
    email: lin.wu@landasoft.com
