eureka:
  #  instance:
  #    nonSecurePort: 80
  #    hostname: ${vcap.application.uris[0]}
  client:
    serviceUrl:
      defaultZone: https://spring-cloud-eureka.lorealoperationsapac.com/eureka/

  #自定义的参数
custom:
  restURL: https://spring-cloud-client-backend.lorealoperationsapac.com/call/